### ISSUE TITLE
Handle schema with invalid tag name in middle version

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#71]
We've got an issue with the following repo:
```yml
prenoms:
  url: https://github.com/CharlesNepote/liste-prenoms-nouveaux-nes.git
  type: tableschema
  email: charles.nepote@fing.org
```

Some tags are not valid at the beginning and the current validation does not handle this. We should be able to skip invalid tags at the beginning if there are valid tags after.
